import { Nunito, Playfair_Display, Great_Vibes } from "next/font/google";
import "./globals.css";

import NavBar from "./(components)/nav-bar/nav-bar";

const greatVibes = Great_Vibes({
  variable: "--font-logo",
  weight: ["400"],
});
const nunito = Nunito({
  variable: "--font-body",
  style: ["normal", "italic"],
  weight: ["200", "300", "400", "500", "600", "700"],
});
const playfairDisplay = Playfair_Display({
  variable: "--font-heading",
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Dream CreationZ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} ${playfairDisplay.variable} ${greatVibes.variable} `}
    >
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
